import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { useEffect, useState } from 'react';
import useSWR from 'swr';
import styles from '../styles/Home.module.css'

const fetcher = (url) => fetch(url).then((res) => res.json());

export default function ApiPage() {
  const [headerData, setHeaderData] = useState([]);

  const { data, error } = useSWR('/api/hello', fetcher);
  console.log('data: ', data);

  useEffect(() => {
    const result = [];
    if (data && data.headers) {
      for (const key in data.headers) {
        result.push({ key, value: data.headers[key] })
      }
      setHeaderData(result)
    }

  }, [data]);

  if (error) return <div>Failed to load</div>;
  if (!data) return <div>Loading...</div>;



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/"><a>Header By server side rendering</a></Link>
        <Link href="/api-page"><a>Header By api serverless</a></Link>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h2>Headers by getServerSideProps</h2>
        <div style={{
          display: 'flex',
          flexDirection: 'column'
        }}>
          {headerData.map(item => {
            return (<div key={item.key} style={{
              display: 'flex'
            }}>
              <div>{item.key}</div>
              <div>{item.value}</div>
            </div>)
          })}
        </div>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
