import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import useSWR from 'swr';
import styles from '../styles/Home.module.css'

const fetcher = (url) => fetch(url).then((res) => res.json());

export async function getServerSideProps(context) {
  console.log('context.req.headers: ', context.req.headers);
  return {
    props: {
      headers: context.req.headers
    }, // will be passed to the page component as props
  }
}

export default function Home({ headers }) {
  // const { data, error } = useSWR('/api/hello', fetcher);
  // if (error) return <div>Failed to load</div>;
  // if (!data) return <div>Loading...</div>;
  // console.log('data: ', data);

  const [data, setData] = useState([]);
  useEffect(() => {
    const result = [];
    for (const key in headers) {
      result.push({ key, value: headers[key] })
    }
    setData(result)
  }, [headers]);

  console.log('data: ', data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div style={{
          display: 'flex',
          flexDirection: 'column'
        }}>
          {data.map(item => {
            return (<div key={item.key} style={{
              display: 'flex'
            }}>
              <div>{item.key}</div>
              <div>{item.value}</div>
            </div>)
          })}
        </div>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
